### PR TITLE
fix: env by prefix panic

### LINKED ISSUE #25: fix: utils.GetEnvsByPrefix can panic
`GetEnvsByPrefix` can panic if the environment has a key matching the given prefix but with a different separator than `_` (which is hardcoded in the func) and when `strip` is true.

Ex:
```go
func main() {
	// note the dash instead of underscore
	os.Setenv("MY_PREFIX-key", "val")
	pairs := utils.GetEnvsByPrefix("MY_PREFIX", true)
	fmt.Println(pairs)
}
```

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/sassoftware/event-provenance-registry/pkg/utils.GetEnvsByPrefix({0x4cdd60, 0x9}, 0x1)
        /home/caproven/dev/git/event-provenance-registry/pkg/utils/utils.go:41 +0x227
main.main()
        /home/caproven/dev/git/event-provenance-registry/main.go:15 +0x45

Process finished with the exit code 2
```

### PR DESCRIPTION
**Pull request by caproven**
GetEnvsByPrefix split on a prefix not guaranteed to exist, risking panics when indexing the resulting slice.

A bit of logic is changed or defined in tests I want input on:
- Caller now must provide exact prefix they want, e.g., `MY_PREFIX_`, instead of `MY_PREFIX`
- If a key matches the prefix exactly (prefix `BLAH` and key `BLAH`), it is inserted into the returned map with an empty string key

Closes #25

### CODE REVIEW

File: pkg/utils/utils.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ func GetEnvsByPrefix(prefix string, strip bool) map[string]string {
 			if len(pair[1]) > 0 {
 				k := pair[0]
 				if strip {
-					k = strings.Split(pair[0], prefix+"_")[1]
```
Comment (gbuskey) [inline pkg/utils/utils.go:41]: Is this function actually used anywhere? This seems like something viper+cobra should be doing for us

**Review by gbuskey — CHANGES_REQUESTED** [review]

File: pkg/utils/utils.go (hunk 1 above)
Comment (caproven) [reply pkg/utils/utils.go:41]: It doesn't seem so. Brett was the author, @xbcsmith were you planning for this to be used? Otherwise can just remove it.

Comment (gbuskey) [reply pkg/utils/utils.go:41]: This seems like a leftover from xunit2receipt. i vote we chop it out

**Review by gbuskey — APPROVED** [review]
